extract version, release regex to util
NUWCDIVNPT/stig-manager pull request #1192
Opened 2024-01-22 22:05 UTC by rajesh-shres

2024-01-22 22:19 UTC, cd-rite requested changes

2024-01-22 22:19 UTC, cd-rite commented on api/source/service/utils.js
>      ro.version = results[1]
Since you are returning just version and release from your new function, we should be assigning results[0] and [1] here now instead of 1 and 2.

2024-01-22 22:19 UTC, cd-rite commented on api/source/service/CollectionService.js
>          version = revisionParts[1]
Since you are returning just version and release from your new function, we should be assigning results[0] and [1] here now instead of 1 and 2.

2024-01-23 17:00 UTC, cd-rite requested changes

2024-01-23 17:00 UTC, cd-rite commented on api/source/service/AssetService.js
>        const revId =  `${inPredicates.benchmarkId}-${results[1]}-${results[2]}`
There are several instances where this structure is used too, and these will need to change to the 0,1 items in the array as well.

2024-01-23 17:00 UTC, cd-rite commented on api/source/service/AssetService.js
>          revId =  `${benchmarkId}-${revParse[1]}-${revParse[2]}`
There are several instances where this structure is used too, and these will need to change to the 0,1 items in the array as well.

2024-01-23 17:00 UTC, cd-rite commented on api/source/service/AssetService.js
>          revId =  `${benchmarkId}-${revParse[1]}-${revParse[2]}`
There are several instances where this structure is used too, and these will need to change to the 0,1 items in the array as well.

2024-01-23 17:00 UTC, cd-rite commented on api/source/service/AssetService.js
>        revId = `${benchmarkId}-${revParse[1]}-${revParse[2]}`
There are several instances where this structure is used too, and these will need to change to the 0,1 items in the array as well.

2024-01-23 17:00 UTC, cd-rite commented on api/source/service/CollectionService.js
>        predicates.binds.version = results[1]
There are several instances where this structure is used too, and these will need to change to the 0,1 items in the array as well.

2024-01-30 18:31 UTC, csmig commented
I've pushed a commit that calls the existing function `parseRevisionStr()` in `api/source/service/utils.js` rather than defining a new function. `parseRevisionStr()` returns an Object with `version` and `release` properties, which helps with readability. If the `parseRevisionStr()` function is considered defective in some way, then that should be addressed separately.

2024-02-01 22:16 UTC, cd-rite commented
Changes merged in PR: #1207

2024-02-01 22:16 UTC, closed without merging