Docs: Updates Stig-manager entity relationship diagram.
NUWCDIVNPT/stig-manager pull request #1239
Opened 2024-03-13 19:50 UTC by Matte22

resolves: #1094 

This PR introduces an updated ERD that represents latest stig manager database schema.

2024-03-15 16:53 UTC, csmig requested changes
I'd like to change the name of the SVG file from `eer-stig-wide.svg` to `eer-stigman-wide.svg`.

stig => stigman

2024-03-18 17:19 UTC, cd-rite approved these changes

2024-03-18 17:19 UTC, cd-rite approved these changes

2024-03-18 17:20 UTC, csmig approved these changes

2024-03-18 17:21 UTC, merged